# -*- coding: utf-8 -*-
"""Assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uyBkljfOgwAQNwQFkH8b9VhnV3fEB11h
"""

#-------------------- Assignment 1------------------------------------------------------
# examples of collective data types in pythone
# -------------------list------------------------------
# -----------------example 1---------------------------
tralist=["manali","kerela","goa","maldives","Dubai","hong kong","Paris"]
print("Your Travel Destinations are",tralist)
print(" ")
# print from indax value
print("your travel destinations are as under : ")
print(tralist[0])
print(tralist[1])
print(tralist[2])
print(tralist[3])
print(tralist[4])
print(tralist[5])
print(tralist[6])
# Update 
tralist[-3]="Swtzerland"
print("Your Updated Travel Destinatins list are",tralist)

# ----------------list-----------------
# ---------------------------example 2------------------
implist=["Java","C++","C","Python","CSS","Java Script","Ruby"]
print("Important Languages of Prgramming are : ",implist)
print("  ")
# print from indax value 
print("important Programming languages are : ")
print(implist[0])
print(implist[1])
print(implist[2])
print(implist[3])
print(implist[4])
print(implist[5])
print(implist[6])

# Update
implist[4]="HTML"
print("Updated important Programmin languages are:",implist)

# --------------------tuple-----------------------
# ------------example 1--------------

fettuple=("Iphone14 pro MAX","Dynamic iceland","better video quality","longest bettry life","256 GB","Aluminium Glass","Dual camera system")
print(fettuple)
print("  ")
#print from indax value 
print("Features of new IPHONE 14 pro is : ")
print(fettuple[0])
print(fettuple[1])
print(fettuple[2])
print(fettuple[3])
print(fettuple[4])
print(fettuple[5])
print(fettuple[6])

# -----------------------------tuple-------------
# --------------example 2----------------------

protuple=("HomePod","Iphone","Apple Watch","Ipad","iMac","mac book","apple TV","AirPods")
print(protuple)
print("  ")
#print from indax value 
print("Here is some Apple Products : ")
print(protuple[0])
print(protuple[1])
print(protuple[2])
print(protuple[3])
print(protuple[4])
print(protuple[5])
print(protuple[6])

#------------------Dictionary---------------------
#-----------------example 1---------------------
indic={"Course":"Python",
       "Fees":"5000",
       "Batch":"January",
       "mode":"Online",
       "class":"live"}
print(indic)

# Update
indic["Course"]="Data Science","Python"
print("The values After Updating are: " ,indic)

#------------------Dictionary---------------------
#-----------------example 2---------------------
capital_dic={"Gujarat":"Gandhinagar",
       "Nepal":"kathmandu",
       "Maharastra":"Mumbai",
       "Goa":"Panji",
       "Rajasthan":"jaipur"}
print(capital_dic)
print(capital_dic["Goa"])
print(capital_dic["Maharastra"])

# ----------------set-------------------
#--------------------example 1--------------
set1={2,4,6,8,10,12,14,16,18,19}
set2={1,3,5,7,9,11,13,14,15,17,18,19}
print("Union of set is :")
set3=set1.union(set2)
print(set3)
print("Intersection of set is :")
set4=set1.intersection(set2)
print(set4)

#----------------set---------------------
#---------------example 2------------------
task1_set={"Assignment","Homework","work","cleaning","Exerciseing","travelling",True}
place1_set={"home","GYM","Collage","Food Zone",False}
time_set={12.30,5.45,2.30,4.30,6.45,7.15}
print(task1_set)
print(place1_set)
print(time_set)